### ISSUE TITLE
5s执行一次

### ISSUE THREAD

**Issue by 530l** [liangjingkanji/Interval#1]
interval = Interval(5, TimeUnit.SECONDS)
东哥，这样是5s回调一次吗

**Comment by liangjingkanji** [comment]
是的, 建议直接运行

**Comment by 530l** [comment]
设置5，没效果，还是每秒会执行回调

**Comment by liangjingkanji** [comment]
由于你提供的信息过少, 我只能猜测你可能没有调用`start()`

**Comment by 530l** [comment]
val t = 1 * 60  
        interval = Interval(5, TimeUnit.SECONDS)
        interval!!.subscribe {
            ALog.i("interval---", count.toString())
            if (count % t <= 0) {
                ALog.i("interval---", "1分钟调下接口")
            }
        }
        interval!!.start()
subscribe方法每秒回进来

**Comment by liangjingkanji** [comment]
我在demo无法复现你的问题, 建议你要么fork仓库复现问题 要么自己排查是否写错

**Comment by 530l** [comment]
是我写错了
