### ISSUE TITLE
pause后resume会有问题

### ISSUE THREAD

**Issue by HolenZhou** [liangjingkanji/Interval#2]
如果在倒计时从10变成9的瞬间点了pause, 再次点resume时，9会立即变成8，没有正确的延时哦

**Comment by HolenZhou** [comment]
应该是pause方法delay的计算反了，现在的delay是当前已经过去的时间，而不是后一次计时前需要延时的时间，这样改好像可以了：

val process = System.currentTimeMillis() - countTime
delay = max(1000 - process, 0L)

**Comment by liangjingkanji** [comment]
你能成为作者之一发起pr修复吗？

**Comment by liangjingkanji** [comment]
你试下最新版本 1.0.3 还存在问题吗?
