### ISSUE TITLE
设置单位为毫秒的时候 ，倒计时不准确 ，东哥怎么处理呢

### ISSUE THREAD

**Issue by SonGuoer** [liangjingkanji/Interval#4]
```kotlin
val interval = Interval(
    0,
    1,
    TimeUnit.MILLISECONDS,
    60000
).life(requireActivity())
```
何手机倒计时 1分钟会慢7秒 ，5分钟会慢2分钟左右

**Comment by liangjingkanji** [comment]
在精确到毫秒计时时, 的确存在延迟很大, 你可以改为秒或以上的轮询频率暂时规避此问题

本问题目前正在`dev`分支中修复(工作繁忙暂时需要等待时间)

**Comment by liangjingkanji** [comment]
这个问题我认为无法解决, 程序无法做到毫秒级别精准回调, 必然存在误差. 另外程序中我不认为有需求一定需求毫秒级别回调, 你改成秒即可

我尝试使用`CountDownTimer`来实现但这会导致无法保证回调次数, 我认为问题更加严重, 并且也无法实现精准到毫秒

我的技术能力有限, 如果你有更好的解决方法可以提出来
