### ISSUE TITLE
部分手机App进入后台时过一段时间会停止计时

### ISSUE THREAD

**Issue by fringesy** [liangjingkanji/Interval#5]
目前发现在一些华为和oppo测试机上，App切到后台时过一段时间计时会停止。
代码：
`
        Interval(0, 1, TimeUnit.SECONDS, 600).subscribe {
            Log.e("Interval", "interval: $it")
        }.start()
`
简单的demo，只有一个MainActivity，在onCreate中创建上述代码，在oppo手机上切到后台30s左右、在华为手机上切到后台17s左右都会停止计时，小米手机上没问题
版本：`implementation 'com.github.liangjingkanji:Interval:1.0.3'`
协程版本：1.6.0/1.7.1

**Comment by fringesy** [comment]
activity的onDestory没有触发，回到前台时计时会继续。

**Comment by liangjingkanji** [comment]
这是Android特性, App后台一段时间后不允许占用CPU

**Comment by fringesy** [comment]
> 这是Android特性, App后台一段时间后不允许占用CPU

好的，了解了
